[package]
name = "simple-vec"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = { version = "0.2.155", default-features = false }

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
